### ISSUE TITLE
Bot leaves room when room key error occurs (v3.14)

### ISSUE THREAD

**Issue by jame25** [matrixgpt/matrix-chatgpt-bot#239]
> Sun, 29 Oct 2023 08:26:03 GMT [ERROR] [MatrixClientLite] Decryption error on !************:matrix.org $x6u-LEMMb-1FyV_TlAcHvQxYRneEWT9zWxWzz_8cJWg [Error: decryption failed because the room key is missing] {
>   code: 'GenericFailure'
> }
> Sun, 29 Oct 2023 08:26:03 GMT [ERROR] [index] Failed decryption event!
> [object Object]

**Comment by bertybuttface** [comment]
Try restarting it a couple of times, if that doesn't clear it follow these steps:

https://github.com/matrixgpt/matrix-chatgpt-bot#i-get-error-decryption-failed-because-the-room-key-is-missing

Unfortunately we are blocked from upgrading matrix-bot-sdk (see: https://github.com/matrixgpt/matrix-chatgpt-bot/pull/170) but you could try that on your local machine. You will need to follow the steps above again after upgrading.

**Comment by jame25** [comment]
Restarting a few times seems to have resolved the issue.

**Comment by bertybuttface** [comment]
Excellent, it's an ugly work around but it seems to work. I don't have much time to test the bot out right now so all feedback like this is very useful. Thankyou!
